- src/index.tsx
Hi team!
We already created this project with React 18, but only partially [because of it](https://reactjs.org/blog/2022/03/29/react-v18.html#react-dom-client):
> `createRoot`: New method to create a root to `render` or `unmount`. Use it instead of `ReactDOM.render`. **New features in React 18 don’t work without it**.
We are not taking advantage of the new features, but I think that it is better to be ready now to avoid difficult migrations in the future.
> Use React 18 createRoot

- src/session/AppSessionStateContext.tsx
Related JIRA: [https://makingsense.atlassian.net/browse/DE-693](https://makingsense.atlassian.net/browse/DE-693)
Issue (intermittently): on user session update event is launched before onSessionUpdate is defined.
Fix: we add a call to onSessionUpdate right after is defined.
> Fix: onSessionUpdate method call

- public/index.html
- src/App.tsx
Hi team!
It is to run the patch URLs code in the local environment. I have also refactored the code to make it more friendly (friendly with me 😛)
I also added simple code to allow us to simulate SPA navigation in the local environment:
As you can see, the menu only reacts to URL changes after a reload, it should be fixed in #121
Thoughts?
---
**Update:** I applied some fixes in the button styles
> Patch WebApp URLs in local

- src/index.tsx
In Reports, the HTML rendering is slower than Menu MFE loading, so, it was failing randomly in this way:
Before the fix:
After the fix:
> Wait for DOMContentLoadedif the target element is not available yet

- .gitignore
- src/client/DopplerLegacyClientImpl.ts
- src/components/HeaderMessages.test.tsx
- src/components/HeaderMessages.tsx
- src/components/ValidateSubscriber/CheckBoxQuestion.tsx
- src/components/ValidateSubscriber/InputQuestion.tsx
- src/components/ValidateSubscriber/Question.tsx
- src/components/ValidateSubscriber/QuestionsForm.test.tsx
- src/components/ValidateSubscriber/QuestionsForm.tsx
- src/components/ValidateSubscriber/ValidateMaxSubscribersForm.test.tsx
- src/components/ValidateSubscriber/ValidateMaxSubscribersForm.tsx
- src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
- src/components/ValidateSubscriber/ValidateSubscribers.tsx
- src/components/ValidateSubscriber/ValidateSubscribersForm.tsx
- src/components/ValidateSubscriber/form-helpers.tsx
- src/components/ValidateSubscriber/types.ts
Refactorización del formulario de suscriptores manteniendo la lógica  extraída de [doppler-webapp](https://github.com/FromDoppler/doppler-webapp).
- Se separó los componentes de preguntas en `InputQuestion `y `CheckboxQuestion`.
- Se simplificó los tipos de componente usando `Question`, este decide que tipo de componente renderizar en base al tipo de pregunta.
- Se aisló y renombraron <s>`ValidateMaxSubscriberForm `</s> por `QuestionForm`
- Se renombraron <s>`ValidateSubscriber `</s> a `ValidateSubscriberForm `ahora este pasa a construir el formulario usando `QuestionForm`
- Se renombraron algunos modelos del _Typado_ del formulario.
- Se actualizaron las pruebas de `HeaderMessages`
> [DE-729] Refactorización de formulario de suscriptores

- src/components/UserPlan.test.tsx
- src/components/UserPlan.tsx
Mejoras:
* El atributo **_sms_** del modelo de usuario antes se consideraba obligatorio ahora es opcional
* El método `SafeSms()` ahora verifica que exista el atributo sms en la data y que este habilitado, si esta habilitado se devuelve el objeto sanitizado o de lo contrario retorna **undefined**.
> [DE-726] refactorización de la informacion de sms

- src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
Las pruebas del componente `ValidateSubscribersForm` se rompían porque intentaba usar el contexto de la configuración (**_`appConfigurationProvider`_**), como solución se usa la configuración _dummy_.
Log de error: http://docker.fromdoppler.com:8080/blue/organizations/jenkins/FromDoppler%2Fdoppler-menu-mfe/detail/PR-174/2/pipeline/
> Actualización de pruebas frágiles

- src/components/ClientManagerUserPlan.tsx
- src/components/HeaderMessages.test.tsx
- src/components/HeaderMessages.tsx
- src/components/Modal.test.tsx
- src/components/Modal.tsx
- src/components/UserMenu.tsx
- src/components/UserPlan.test.tsx
- src/components/UserPlan.tsx
Se realizó una refactorización general del componente UserPlan para tener lógica mas pequeña.
* Se separo el componente `<UserPlan/>` cuando el usuario tiene _**ClientManager**_ activo.
* Se permite definir un id de prueba en cada implementación del componente `<Modal/>`
* Se reescribió el botón de actualización de plan como un componente para mas semántica.
> [DE-726] refactorización de componente plan de usuario

- src/client/dopplerLegacyClient.ts
- src/components/HeaderMessages.test.tsx
- src/components/ValidateSubscriber/QuestionsForm.tsx
- src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
- src/components/ValidateSubscriber/ValidateSubscribersForm.tsx
Antes cuando se intentaba abrir el formulario validación de subscriptores desde la alerta mostraba un error inesperado ([Hilo](https://makingsense.slack.com/archives/CRXR62TC2/p1663342220796679)).
Para solucionar el error se reorganizó el uso de _React-query_ en hooks para mantener el scope adecuadamente.
> [DE-726] corrección de error al mostrar formulario validación de subscriptores 

- src/components/MenuRight.tsx
- src/components/Notifications.tsx
Se reorganizaron los componentes de la bandeja de notificaciones siguiendo los lineamientos del [StyleGuide](https://cdn.fromdoppler.com/doppler-style-guide/documentation/int/header-component.html).
https://user-images.githubusercontent.com/6733401/193164425-c46a088d-04e4-4f5b-a766-f3ff91e3956a.mp4
> [DE-803] corregir bandeja de notificaciones cuando se tienen mas de una

- src/client/DopplerLegacyClientDummy.ts
- src/components/HeaderMessages.test.tsx
- src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
- src/components/ValidateSubscriber/ValidateSubscribersForm.tsx
- src/components/i18n/es.ts
The user was able to submit this form multiple times while it was being submited.
The form is really ugly and needs more love, but it will fix this particular issue.
> DE-815 - Avoid multiple submit of EAV validation

- src/components/Header.test.tsx
- src/components/Nav.test.tsx
- src/hooks/useMeta.test.tsx
- src/hooks/useMeta.tsx
- src/navbar-state/navbar-state-abstractions.ts
- src/navbar-state/navbar-state-hook.ts
- src/navbar-state/navbar-state-reducer.test.tsx
- src/navbar-state/navbar-state-reducer.ts
It searchs for meta elements in DOM to override the URL-based active menu item.
Elements like `<meta name="doppler-menu-mfe:default-active-item" content="listMasterSubscriberMenu" />` would set the active menu item if the URL does not match an existing one.
Elements like `<meta name="doppler-menu-mfe:force-active-item" content="listMasterSubscriberMenu" />` will set the active menu item whatever is the URL.
> DE-806 - Read forced or default menu item on Menu MFE initialization

- src/App.test.tsx
- src/client/dopplerLegacyClient.ts
- src/components/HeaderMessages.test.tsx
- src/components/HeaderMessages.tsx
- src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
Se replica la lógica de [Webapp ](https://github.com/FromDoppler/doppler-webapp/blob/409f3818aeb4eab76db317de11bbc017393d7af5/src/components/Header/HeaderMessages/HeaderMessages.js#L26-L33)para la confirmación de la alerta de máximo de subscriptores
Al recargar la alerta desaparece.
https://user-images.githubusercontent.com/6733401/193501104-b4c897e2-ad68-434a-aca1-21a581e7df2c.mp4
> [DE-809] envió de confirmación al back desde la confirmación en mensaje de alerta

- src/components/Notifications.tsx
Antes al hacer clic sobre la campanita de notificaciones no se mostraba la bandeja de notificaciones, ahora funciona desde el primer clic.
https://user-images.githubusercontent.com/6733401/193596390-68c16d31-d22e-4e6f-bf4a-dc3d4ad7a57f.mp4
> [DE-818] Corregida campanita de notificaciones

- src/App.tsx
- src/client/dopplerLegacyClient.ts
- src/components/HeaderMessages.tsx
Cuando damos clic en el botón **_Entendido_** (de tipo _closeModal_) en un mensaje de alerta ocultamos el mensaje sin recargar la página.
https://user-images.githubusercontent.com/6733401/193661104-85cb74c6-40ee-47eb-9791-853b04e2bb8a.mp4
> [DE-809] ocultar mensaje de alerta cuando se da click en boton entendido

- src/hooks/useMeta.test.tsx
- src/hooks/useMeta.tsx
- src/hooks/useMutationObserver.ts
It listens to DOM updates in order to update the active menu item.
- See https://github.com/FromDoppler/doppler-webapp/pull/2140
- See related documentation in #195: https://github.com/FromDoppler/doppler-menu-mfe/pull/195/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R55
- Fixed! thanks @leoslopez !
- We will keep the refactoring
> DE-810 - Menu item on DOM update

- src/hooks/useMeta.test.tsx
It removes some of the warnings in the tests, but not all:
After:
Before:
> Add missing act wrappers

- src/client/DopplerLegacyClientImpl.ts
The backend is clearly expecting a JSON ([see the code](https://github.com/MakingSense/Doppler/blob/55e7819c1c590e81f2fc16713ee0483b0bca8c14/Doppler.Presentation.MVC/Controllers/SendMaxSubscribersEmailController.cs#L106-L113) it is ugly but expects a JSON).
It seems that the previous Axios version did not make honor to this header and the new one does.
---
The header was there to avoid CORS Preflight, I restore the previous behavior to avoid doing changes in the Doppler backend.
> fix: remove wrong content-type header

- src/components/HeaderMessages.tsx
- src/components/UserPlan.tsx
Hi team!
It seems that Reports has a Form in the complete page body, and we missed the _type_ in some _buttons_, so they worked as _submit_.
It should fix the issue, testing...
> fix: add missing type to the buttons

- src/App.tsx
It seems there is an issue on the first render when accessing the conversations secction. It doesnt display the menu and throws an error in the console (Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.)
It seems to be related to the header notification because it doesn't happen when there is no notification to display.
It might be related to this: https://stackoverflow.com/questions/54880669/react-domexception-failed-to-execute-removechild-on-node-the-node-to-be-re#:~:text=Problem%20explanation%3A
If it doesn't work i will revert this.
> [DOI-1224] Fix for conversations secction not display doppler menu

- src/App.test.tsx
- src/App.tsx
- src/components/UserMenu.tsx
- src/components/UserSelection.tsx
To avoid an overlapping with the notification banner we need to have the modal at the same level as the `HeaderMessages` component, that being the `App` component.
> [DOI-1533] Move user selection modal to app component
