FromDoppler/doppler-menu-mfe

src/App.test.tsx, src/components/Header.js, src/components/Header.test.js, src/components/Logo.js, src/components/Logo.test.js, src/components/Nav.js, src/components/Nav.test.js, src/components/Notifications.test.js, src/components/UserMenu.test.js
=> Unit test in progress

package.json, src/components/i18n/MenuIntlProvider.test.tsx, src/components/i18n/MenuIntlProvider.tsx, src/components/i18n/es.tsx, src/components/i18n/utils.tsx, src/index.tsx, yarn.lock
=> i18n simplified implementation

src/components/Header.tsx, src/components/MenuRight.test.tsx, src/components/MenuRight.tsx, src/components/Nav.tsx
RELATED JIRA: [DE-617](https://makingsense.atlassian.net/browse/DE-617)
=> Responsive behaviour

src/App.tsx, src/components/Header.test.tsx, src/components/Header.tsx
Related Jira: [DE-654](https://makingsense.atlassian.net/browse/DE-654)
=> Menu Header placeholder while loading user data

src/components/HeaderMessages.tsx, src/components/Tooltip.tsx, src/components/UserMenu.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/model.ts
Related JIRA: [DE-657](https://makingsense.atlassian.net/browse/DE-657)
- UserPlan components features updates
- UserPlan unit test added
=> User menu updates

src/App.tsx, src/testUserData.json
Related JIRA: [DE-694](https://makingsense.atlassian.net/browse/DE-694)
=> Active menu items based on relative urls

src/App.tsx
Related JIRA:  [https://makingsense.atlassian.net/browse/DE-694](https://makingsense.atlassian.net/browse/DE-694)
Description:  we search for `webapp` on user data nav urls strings an replace the host with `testmenu` in order to be able to test menu expected behavior (menu item should be styled as selected when the url property match browser current url)
=> Replace items url when domain is testmenu

src/session/SessionMfeAppSessionStateClient.ts, src/session/doppler-session-mfe-conventions.ts
See details: https://github.com/FromDoppler/doppler-session-mfe/pull/101
Related: https://github.com/FromDoppler/doppler-editors-webapp/pull/305
=> chore: update Session MFE types

src/App.test.tsx, src/components/i18n/MenuIntlProvider.tsx, src/components/i18n/utils.tsx, src/session/SessionMfeAppSessionStateClient.ts, src/session/app-session-abstractions.ts, src/session/dummyAppSessionStateClient.ts
This change allows adding another language (English) in a future PR.
=> Support multilanguage content

src/components/HeaderMessages.tsx, src/components/UnexpectedError.test.tsx, src/components/UnexpectedError.tsx, src/components/ValidateSubscriber/ValidateMaxSubscribersConfirmation.test.tsx, src/components/ValidateSubscriber/ValidateMaxSubscribersConfirmation.tsx, src/components/ValidateSubscriber/ValidateMaxSubscribersForm.tsx, src/components/ValidateSubscriber/ValidateSubscribers.tsx, src/components/ValidateSubscriber/form-helpers.tsx, src/components/ValidateSubscriber/reducer/validateMaxSubscribersFormReducer.test.ts, src/components/ValidateSubscriber/reducer/validateMaxSubscribersFormReducer.ts, src/components/ValidateSubscriber/types.ts, src/components/ValidateSubscriber/validate-max-subscribers-doubles.ts, src/components/ValidateSubscriber/validations.ts, src/components/i18n/es.tsx, src/testUserData.json
- Related JIRA: [https://makingsense.atlassian.net/browse/DE-729](https://makingsense.atlassian.net/browse/DE-729)
=> Modal form to subscribers origin validation - view only

src/App.test.tsx, src/App.tsx, src/components/Header.test.tsx, src/components/Header.tsx, src/components/HeaderMessages.test.tsx, src/components/HeaderMessages.tsx, src/components/MenuRight.test.tsx, src/components/MenuRight.tsx, src/components/Nav.test.tsx, src/components/Nav.tsx, src/components/Notifications.tsx, src/components/UpgradePlanForm.test.tsx, src/components/UserMenu.test.tsx, src/components/UserMenu.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/model.ts, src/session/SessionMfeAppSessionStateClient.ts, src/session/dummyAppSessionStateClient.ts, src/utils.ts
Hi team!
These changes are to make the menu model safer and more predictable.
After this, I will make a code refactoring in order to mutate menu items' states using a reducer.
=> DE-751 - Cleanup model

src/App.tsx, src/temporalPatchingUtils.ts, src/utils.ts
Hi team!
I think it will help us to simplify the changes related to the state.
Could you review?
=> refactor: move temporal URL patching to the lowest layer

src/testUserData.json
Related to https://github.com/MakingSense/Doppler/pull/9621
=> fix: fix dashboard menu id

src/components/HeaderMessages.test.tsx, src/components/HeaderMessages.tsx, src/components/ValidateSubscriber/ValidateSubscribers.test.tsx, src/components/ValidateSubscriber/ValidateSubscribersForm.tsx, src/model.ts, src/testUserData.json, src/utils.ts
Se muestran todas las alertas que están disponibles para mostrar.
**related to**: [DE-767](https://makingsense.atlassian.net/browse/DE-767)
https://user-images.githubusercontent.com/6733401/189446915-fe328f8b-b372-4b68-8192-c6ab08d15190.mp4
=> [DE-767] mostrar alerta siguiente

src/components/Header.test.tsx, src/components/HeaderMessages.test.tsx, src/components/MenuRight.test.tsx, src/components/UpgradePlanForm.test.tsx, src/components/UserMenu.test.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/model.ts, src/utils.ts
Para mejorar la semántica y facilitar el mantenimiento de los planes se refactoriza el modelo de planes.
=> [DE-726] refactorización - uso restringido de string para identificar el tipo de plan de usuario

src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/mocks/userMock.ts
La refactorización incluye:
* Prueba para planes mensuales
* Prueba para planes por contactos (subscriptores)
* Prueba para otros tipos de planes (incluye tipo de plan indefinido)
* Se separa la lógica que renderiza la información de plan en un componente aislado.
=> [DE-726] Refactorización y pruebas para información de plan de usuario

src/App.tsx, src/AppConfiguration.tsx, src/index.tsx
It will allow us to hear when the menu data is loaded and then show the page content.
=> feat: allow defining a callback for changing status

src/components/ClientManagerLogo.tsx, src/components/Header.tsx, src/components/UserMenu.tsx, src/components/UserPlan.tsx, src/model.ts, src/utils.ts
=> DE-821 - Fix Client Manager support

src/components/HeaderMessages.test.tsx, src/components/ValidateSubscriber/ValidateSubscribers.test.tsx
It fixes this warning message:
But now it is showing this one:
I think that it is fine and it was hidden before.
I hope (but I am not sure) this change also fixes another issue:
=> test: replace the mocks of dopplerLegacyClient by mocks of DopplerLegacyClientImpl

README.md, package.json, src/App.tsx, src/AppConfiguration.tsx, src/components/Header.test.tsx, src/components/Header.tsx, src/components/MenuRight.test.tsx, src/components/MenuRight.tsx, src/components/Notifications.test.tsx, src/components/Notifications.tsx, src/components/i18n/MenuIntlProvider.tsx, src/model.ts, src/testUserData.json, src/utils.ts, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1262
⚠️ ⚠️**Note:** Work is being done on customizing the tool to adjust colors and categories of notifications
**RESULT:**
=> Dat 1262 beamer implementation

package.json, src/components/Header.test.tsx, src/components/HeaderMessages.test.tsx, src/components/MenuRight.test.tsx, src/components/Notifications.tsx, src/components/UpgradePlanForm.test.tsx, src/components/UserMenu.test.tsx, src/mocks/userMock.ts, src/model.ts, src/utils.ts, yarn.lock
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1374
=> Dat 1374 add user id to beamer

src/components/Notifications.tsx
**Jira Ticket:**. https://makingsense.atlassian.net/browse/DAT-1392
=> feat: add filter parameter

src/components/Header.tsx, src/components/Nav.tsx, src/components/SubNavDesktop.tsx
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1529
**Result**
=> Dat 1529 add new menu

src/components/HeaderMessages.tsx, src/components/UserPlan.tsx, src/model.ts, src/utils.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1701
**Description**
Add accountType query param in url when the url is `"/plan-selecion"`
=> feat: add account type in urls

src/components/ChatPlan.tsx, src/components/Header.test.tsx, src/components/HeaderMessages.test.tsx, src/components/MenuRight.test.tsx, src/components/UpgradePlanForm.test.tsx, src/components/UserMenu.test.tsx, src/components/UserPlan.tsx, src/mocks/userMock.ts, src/model.ts, src/testUserData.json, src/utils.ts
=> [DOI-1065] Add conversations plan description to user's menu

src/components/ChatPlan.test.tsx, src/components/ChatPlan.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/model.ts, src/testUserData.json, src/utils.ts
refactor chat plan menu on latest changes
=> [DOI-1139] Chat plan menu

src/components/Notifications.tsx, src/model.ts, src/utils.ts
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-1741
=> Dat 1741 add custom user attributes

src/App.tsx
Didn't work https://github.com/FromDoppler/doppler-menu-mfe/pull/503 😕 
Another try...
=> [DOI-1224] menu rendering error

README.md, src/App.tsx
This will allow to hide the menu simply with a js function call.
it attempts to solve an issue with the landing integration but could be usefull for any other scenario.
=> [DOI-1291] Add window function to hide or display app

src/App.tsx
Revert https://github.com/FromDoppler/doppler-menu-mfe/pull/504
=> Revert Last PR

src/components/UserPlan.tsx
**Jira Ticket:** https://makingsense.atlassian.net/browse/DAT-2009
=> feat: hide addon item for free user

src/components/Modal.tsx, src/components/UserMenu.test.tsx, src/components/UserMenu.tsx, src/components/UserSelection.test.tsx, src/components/UserSelection.tsx, src/components/i18n/en.ts, src/components/i18n/es.ts, src/model.ts, src/testUserData.json, src/utils.ts
=> [DOI-1378] Add related users modal

src/components/UserMenu.tsx
Display collaborator profile in menu when applicable.
=> [DOI-1318] Show as collaborator profile

src/client/DopplerLegacyClientDummy.ts, src/client/DopplerLegacyClientImpl.ts, src/client/dopplerLegacyClient.ts, src/components/UserMenu.tsx, src/components/UserSelection.test.tsx, src/components/UserSelection.tsx, src/session/SessionMfeAppSessionStateClient.ts, src/session/app-session-abstractions.ts, src/session/doppler-session-mfe-conventions.ts, src/session/dummyAppSessionStateClient.ts
https://github.com/user-attachments/assets/0755b6c3-5b9a-4514-9cc2-78373215caf6
=> [DOI-1521] Change session from user menu

src/components/UserMenu.tsx
now it will be shown to any collaborator regardless of the amount of users associated.
=> [DOI-1526] Change logic for display user selection button

src/components/Avatar.tsx, src/components/UserSelection.test.tsx, src/components/UserSelection.tsx, src/model.ts, src/testUserData.json
Add avatar icons to user selection.
=> [DOI-1527] Add avatar to users selection component

src/components/LandingPlan.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx
fix issue with stepper
Task: [DAT-2136](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2136)
[DAT-2136]: https://makingsense.atlassian.net/browse/DAT-2136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2136] - fix issue with stepper

src/session/SessionMfeAppSessionStateClient.ts, src/utils.ts
chore: remove unused console log
=> remove unused console

src/App.tsx
=> Add user name to userpilot

.env, .env.development, .env.int, .env.production, .env.qa, Dockerfile, build-n-publish.sh, doppler-jenkins-ci.groovy, package.json, src/AppConfiguration.tsx, src/index.tsx, yarn.lock
Task: [DAT-2327](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2327)
[DAT-2327]: https://makingsense.atlassian.net/browse/DAT-2327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Support multiple environments

src/App.tsx, src/index.tsx
=> Remove userpilot logs

src/App.tsx
Task: [DAT-2335](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2335)
[DAT-2335]: https://makingsense.atlassian.net/browse/DAT-2335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2335] Add user props

src/components/Header.test.tsx, src/components/MenuRight.test.tsx, src/components/OnSitePlan.test.tsx, src/components/OnSitePlan.tsx, src/components/UserMenu.test.tsx, src/components/UserPlan.test.tsx, src/components/UserPlan.tsx, src/mocks/userMock.ts, src/utils.ts
Add buy onsite in the user menu
**Task:** [DAT-2268](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2268)
[DAT-2268]: https://makingsense.atlassian.net/browse/DAT-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2268] - Add buy onsite in the user menu

src/App.tsx, src/utils.ts
=> Fix active addons prop

src/hooks/useUserpilot.tsx, src/model.ts
=> Send user account id to userpilot

src/components/UserPlan.tsx
Show my plan when the user is free
**Task:** [DAT-2570](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2570)
[DAT-2570]: https://makingsense.atlassian.net/browse/DAT-2570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2570] - Show my plan when the user is free

src/hooks/useUserpilot.tsx, src/model.ts, src/utils.ts
Add more information to userpilot.
**Task:** [DAT-2553](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2553)
[DAT-2553]: https://makingsense.atlassian.net/browse/DAT-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2553] - Add more information to userpilot

src/components/Notifications.tsx, src/hooks/useUserpilot.tsx
Send industry description when initialize beamer.
**Task:** [DAT-2582](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2582)
[DAT-2582]: https://makingsense.atlassian.net/browse/DAT-2582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2582] - Send industry description when initialize beamer

src/components/Notifications.tsx
Task: [DAT-2636](https://makingsense.atlassian.net/jira/software/projects/DAT/boards/62?selectedIssue=DAT-2636)
[DAT-2636]: https://makingsense.atlassian.net/browse/DAT-2636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DAT-2636] Check for null users before init beamer
